# 固定のバージョンを使用する場合
# fastlane_version '2.28.3'
# xcode_select '/Applications/Xcode_13.1.app'
default_platform :ios

platform :ios do
  lane :setup do
    setup_ci(
      force: true,
      provider: 'travis'
    )

    import_certificate(
      certificate_path: 'certificates/distribute.p12',
      certificate_password: ENV["CERTIFICATE_PASSWORD"] || "",
      keychain_name: ENV["MATCH_KEYCHAIN_NAME"] || ""
    )

    profile_name = 'flutter-start-app'
    profile_path = 'certificates/distribute.mobileprovision'

    install_provisioning_profile(path: profile_path)

    disable_automatic_code_signing(
      use_automatic_signing: false,
      profile_name: profile_name,
      code_sign_identity: 'iPhone Distribution'
    )
  end

  lane :gh_actions_store_app_distribution do
    gym(
      scheme: 'Runner',
      configuration: 'Release',
      export_method: 'app-store'
    )

    api_key = app_store_connect_api_key(
      key_id: ENV['ASC_KEY_ID'],
      issuer_id: ENV['ASC_ISSUER_ID'],
      key_content: ENV['ASC_API_KEY']
    )

    deliver(
      platform: 'ios',
      submit_for_review: false,
      skip_screenshots: true,
      force: true,
      skip_metadata: true,
      api_key: api_key,
      precheck_include_in_app_purchases: false
    )
  end
end
